# -*- coding: utf-8 -*-
"""düşme.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pf2E5WtaNVLmGVXI2Vfqq_0iczgNWtZb
"""

print("Adım 1: Gerekli kütüphaneler yükleniyor...")
!pip install opencv-python-headless
!pip install ultralytics
print("Kütüphane yüklemeleri tamamlandı.\n")

from google.colab import files
import os
import cv2
from ultralytics import YOLO
import numpy as np
from IPython.display import Video, display

print("Adım 2: Lütfen videoyu yükleyiniz.")
uploaded = files.upload()

video_path = None
for filename in uploaded.keys():
    print(f'Yüklenen dosya: {filename}')
    video_path = filename
    break

if video_path is None:
    print("Video yüklenemedi. Lütfen tekrar deneyin.")
else:
    print(f"Video '{video_path}' başarıyla yüklendi.\n")

    print("Adım 3: Düşen adamı algılama ve video işleme başlıyor...")

    # YOLOv8 modelini yükle
    model = YOLO('yolov8n.pt')

    # Video dosyasını oku
    cap = cv2.VideoCapture(video_path)

    if not cap.isOpened():
        print(f"Hata: Video dosyası '{video_path}' açılamadı.")
    else:
        # Video özelliklerini al
        frame_width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
        frame_height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
        fps = int(cap.get(cv2.CAP_PROP_FPS))

        print(f"Video bilgileri: {frame_width}x{frame_height}, {fps} FPS")

        # Çıkış videosu için ayarlar
        output_filename = "output_video_with_fall_detection.mp4"
        fourcc = cv2.VideoWriter_fourcc(*'mp4v')
        out = cv2.VideoWriter(output_filename, fourcc, fps, (frame_width, frame_height))

        # Geliştirilmiş takip parametreleri
        person_tracker = {}

        # Düşme parametreleri
        fall_threshold_y = max(10, frame_height // 60)
        fall_duration_frames = max(2, int(fps * 0.1))
        fall_display_frames = fps * 2
        min_fall_speed = 3
        aspect_ratio_change_threshold = 0.08

        print(f"Algılama parametreleri:")
        print(f"- Düşme eşiği (dikey hız): {fall_threshold_y} piksel/frame")
        print(f"- Düşme süresi: {fall_duration_frames} frame ({fall_duration_frames/fps:.2f} saniye)")
        print(f"- Minimum dikey hız: {min_fall_speed} piksel/frame")
        print(f"- En/boy oranı değişim eşiği: {aspect_ratio_change_threshold:.2f}")

        frame_count = 0
        total_detections = 0
        total_falls_detected = 0

        while True:
            ret, frame = cap.read()
            if not ret:
                break

            frame_count += 1

            # YOLO ile algılama
            results = model.track(frame, persist=True, classes=0, conf=0.5, verbose=False)

            current_frame_person_ids = set()

            if results and results[0].boxes is not None and results[0].boxes.id is not None:
                boxes = results[0].boxes.xyxy.cpu().numpy().astype(int)
                track_ids = results[0].boxes.id.cpu().numpy().astype(int)
                confidences = results[0].boxes.conf.cpu().numpy()
                total_detections += len(track_ids)

                for box, track_id, conf in zip(boxes, track_ids, confidences):
                    current_frame_person_ids.add(track_id)

                    x1, y1, x2, y2 = box
                    center_y = (y1 + y2) // 2
                    center_x = (x1 + x2) // 2
                    box_height = y2 - y1
                    box_width = x2 - x1
                    aspect_ratio = box_width / max(box_height, 1)

                    if track_id not in person_tracker:
                        person_tracker[track_id] = {
                            'prev_y': center_y,
                            'prev_x': center_x,
                            'prev_aspect_ratio': aspect_ratio,
                            'is_falling': False,
                            'fall_start_frame': -1,
                            'fall_detected_at': -1,
                            'consecutive_fall_frames': 0,
                            'max_fall_speed': 0,
                            'last_seen_frame': frame_count,
                            'detection_history': [(frame_count, center_y, aspect_ratio)]
                        }
                    else:
                        person_tracker[track_id]['detection_history'].append((frame_count, center_y, aspect_ratio))
                        person_tracker[track_id]['last_seen_frame'] = frame_count

                        prev_y = person_tracker[track_id]['prev_y']
                        prev_x = person_tracker[track_id]['prev_x']
                        prev_aspect_ratio = person_tracker[track_id]['prev_aspect_ratio']

                        # Hareket ve değişim hesaplamaları
                        y_diff = center_y - prev_y
                        x_diff = abs(center_x - prev_x)
                        aspect_change = abs(aspect_ratio - prev_aspect_ratio)

                        is_moving_down_fast = y_diff > fall_threshold_y
                        is_moving_down_min_speed = y_diff > min_fall_speed
                        is_aspect_ratio_changing = aspect_change > aspect_ratio_change_threshold

                        if (is_moving_down_fast or is_aspect_ratio_changing) and is_moving_down_min_speed:
                            person_tracker[track_id]['consecutive_fall_frames'] += 1
                            person_tracker[track_id]['max_fall_speed'] = max(person_tracker[track_id]['max_fall_speed'], y_diff)

                            if person_tracker[track_id]['fall_start_frame'] == -1:
                                person_tracker[track_id]['fall_start_frame'] = frame_count

                            if person_tracker[track_id]['consecutive_fall_frames'] >= fall_duration_frames:
                                if not person_tracker[track_id]['is_falling']:
                                    person_tracker[track_id]['is_falling'] = True
                                    person_tracker[track_id]['fall_detected_at'] = frame_count
                                    total_falls_detected += 1
                                    print(f"🚨 DÜŞME ALGILANDI! ID: {track_id}, Frame: {frame_count}, Max Hız: {person_tracker[track_id]['max_fall_speed']:.1f}px/frame")
                        else:
                            if person_tracker[track_id]['consecutive_fall_frames'] > 0:
                                pass
                            person_tracker[track_id]['consecutive_fall_frames'] = 0
                            person_tracker[track_id]['fall_start_frame'] = -1
                            person_tracker[track_id]['max_fall_speed'] = 0

                        person_tracker[track_id]['prev_y'] = center_y
                        person_tracker[track_id]['prev_x'] = center_x
                        person_tracker[track_id]['prev_aspect_ratio'] = aspect_ratio

                    # Görselleştirme
                    color = (0, 0, 255) if person_tracker[track_id]['is_falling'] else (0, 255, 0)
                    cv2.rectangle(frame, (x1, y1), (x2, y2), color, 2)

                    status = "DÜŞTÜ!" if person_tracker[track_id]['is_falling'] else "Takipte"
                    cv2.putText(frame, f'ID: {track_id} - {status}', (x1, y1 - 10),
                               cv2.FONT_HERSHEY_SIMPLEX, 0.6, color, 2)

                    if person_tracker[track_id]['is_falling'] and (frame_count - person_tracker[track_id]['fall_detected_at']) < fall_display_frames:
                        cv2.putText(frame, 'DÜŞTÜ!', (x1, y2 + 25),
                                   cv2.FONT_HERSHEY_SIMPLEX, 1.0, (0, 0, 255), 3)
                        cv2.rectangle(frame, (0, 0), (frame_width, frame_height), (0, 0, 255), 5)

            # =========================================================================
            # EKLENEN ÖZELLİK: Kaybolan/Suya Batan Kişileri Kontrol Et (Disappearance)
            # =========================================================================
            for tid, tinfo in person_tracker.items():
                if tid not in current_frame_person_ids and not tinfo['is_falling']:
                    # Eğer kişi son görüldüğü andan hemen sonra yok olduysa
                    # ve yok olmadan önce aşağı doğru hareket halindeyse (potansiyel düşme)
                    if (frame_count - tinfo['last_seen_frame']) == 1:
                        if tinfo['consecutive_fall_frames'] > 0 or tinfo['prev_y'] > (frame_height * 0.4):
                            tinfo['is_falling'] = True
                            tinfo['fall_detected_at'] = frame_count
                            total_falls_detected += 1
                            print(f"🚨 SUYA/AŞAĞI DÜŞÜP KAYBOLDU! ID: {tid}, Frame: {frame_count}")

            # Frame sayısını göster
            cv2.putText(frame, f'Frame: {frame_count}', (10, 30),
                       cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255, 255, 255), 2)

            # Toplam düşme sayısını göster
            cv2.putText(frame, f'Toplam Dusme: {total_falls_detected}', (10, 60),
                       cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 0, 255), 2)

            out.write(frame)

            if frame_count % 100 == 0:
                print(f"İşlenen frame: {frame_count}")

        cap.release()
        out.release()

        print(f"\n✅ Video işleme tamamlandı!")
        print(f"📊 İstatistikler:")
        print(f"- Toplam frame: {frame_count}")
        print(f"- Toplam algılama: {total_detections}")
        print(f"- Takip edilen kişi sayısı: {len(person_tracker)}")
        print(f"- Düşme algılanan olay sayısı: {total_falls_detected}")

        print(f"\nAdım 4: Video önizleme ve indirme")
        try:
            display(Video(output_filename))
            print("✅ Video başarıyla yüklendi ve oynatılıyor.")
        except Exception as e:
            print(f"⚠️ Video önizleme hatası: {e}")

        try:
            files.download(output_filename)
            print(f"📥 '{output_filename}' dosyası indirilmeye başlandı.")
        except Exception as e:
            print(f"❌ İndirme hatası: {e}")
            print("Sol paneldeki dosyalar bölümünden manuel olarak indirebilirsiniz.")